### ISSUE TITLE
Minimum deployment target is not 9.0

### ISSUE THREAD

**Issue by ahmadmuhsink** [TheCodedSelf/SwiftCron#19]
Hi @TheCodedSelf , 

`SwiftCron can be used on iOS 9.0 and above.`

but the library is usable only when deployment target is 10.2 because of this project scheme :
1. https://github.com/TheCodedSelf/SwiftCron/blob/master/SwiftCron.xcodeproj/project.pbxproj#L259
2. https://github.com/TheCodedSelf/SwiftCron/blob/master/SwiftCron.xcodeproj/project.pbxproj#L306

**Comment by TheCodedSelf** [comment]
Hi @ahmadmuhsink, I've updated the project, give it a try 🙂

**Comment by ahmadmuhsink** [comment]
Its working well now, thanks 😄
