### ISSUE TITLE
getNextRunDate is always returning nil 

### ISSUE THREAD

**Issue by cliftonmyers** [TheCodedSelf/SwiftCron#26]
Can you tell me what is wrong with this usage? you can try any of the below cronStrings.
And why it is always returning nil

`//"30 9 ? * MON,WED,FRI *"
//"30 15 ? * TUE,THU *"
//"0 10 ? * MON-FRI *"
//"30 18 ? * MON-FRI *"
//"0 20 ? * * *"
let cronString = "0 8 ? * * *"
var calendar = Calendar.current
calendar.timeZone = NSTimeZone.local
let startOfDate = calendar.startOfDay(for: date)
let cronExpression = CronExpression(cronString: cronString)
if let nextRunDate = cronExpression?.getNextRunDate(startOfDate) {
            // should go the code to run on "nextRunDate"
}`

**Comment by TheCodedSelf** [comment]
Hi @cliftonmyers, the `?` operator is not supported, as such `0 8 ? * * *` will fail.

Additionally, please use the format specified on the [Cron Wikipedia page](https://en.wikipedia.org/wiki/Cron).

`30 9 * * MON,WED,FRI *` (note I have removed the `?` from your example) should be `30 9 * * 1,3,5 *`, which will run 09:30AM every Monday, Wednesday, and Friday.

**Comment by TheCodedSelf** [comment]
You'll just need to do some find and replace before creating a `CronExpression` with the expressions you're receiving. Alternatively feel free to implement the features you'd want, I'd welcome the contribution.

**Comment by cliftonmyers** [comment]
Actually, i searched many pods parsing crons, but yours was the best, others were beginners.

I thought that it would cover all the formats, but surprisingly it is not.

When i have time i can add support to additional features, but currently i m tight on my deadline, and the "/" will be a blocker for me.

Can you find a way to help implementing it soon, and i promise i will be contributing in the future with making this library better.

**Comment by TheCodedSelf** [comment]
There is currently a [ticket open for the / operator](https://github.com/TheCodedSelf/SwiftCron/issues/16).

I don't have the capacity to work on this myself at present and I'd most likely miss your deadline. What I could do is guide you through the code base and the best way of implementing it. If you're willing to give it a bash, just let me know.

**Comment by cliftonmyers** [comment]
so basically, you are not using the quartz variation for the cronExpression.

Can you tell me which variation you are using, maybe if i get another response with this variation, it could work better.

**Comment by TheCodedSelf** [comment]
The library is using the standard format specified on the [Cron Wikipedia page](https://en.wikipedia.org/wiki/Cron#Overview). 

Implementing the special operators from the Quartz variation is desired, but not yet complete.
